"use client";

/**
 * Registry hero banner (redesigned — separated text + looping cellar visual).
 *
 * The previous hero overlaid the copy on top of the busy `/01-hero.png` engraving
 * behind a cream scrim, which read as muddy and hard to scan. This redesign SPLITS
 * the two: the copy lives in a clean TEXT column on the flat parchment ground
 * (theme-aware `--ink`/`--muted`/`--red` — fully legible, no scrim gymnastics),
 * and the engraving lives in its own bordered VISUAL frame beside it (below it on
 * narrow screens). See `.hero-grid` / `.hero-visual` in globals.css.
 *
 * LOOPING MOTION: we PREFER a muted, autoplay, looping same-origin `<video>`
 * (`/cinematic/hero-loop.mp4`) — muted video is allowed to autoplay. That asset is
 * generated by a separate task; when it is absent we FALL BACK to the static
 * `/01-hero.png` with a slow CSS "Ken-Burns" loop (gentle infinite zoom/pan) plus a
 * warm flicker overlay, so the frame still reads as a living, looping hero. To flip
 * to the video once it ships, set `HERO_VIDEO` below to the path — nothing else
 * changes. Either way `prefers-reduced-motion: reduce` freezes it to a static image
 * (the animations are gated behind `@media (prefers-reduced-motion: no-preference)`).
 *
 * All media is self-hosted under `/public` (same-origin — required under the live
 * COEP `require-corp` isolation, T-02-05). `pairCount` is bound by the caller to
 * the live valid-pair count.
 */

// Set to a same-origin path (e.g. "/cinematic/hero-loop.mp4") once the looping
// cinematic asset exists; leave null to use the CSS Ken-Burns fallback on the still.
const HERO_VIDEO: string | null = null;

export function RegistryHero({ pairCount }: { pairCount: number }) {
  return (
    <section className="hero-grid" aria-label="The Cellar Registry">
      {/* TEXT — on the flat parchment ground, no scrim, fully legible. */}
      <div className="hero-copy">
        <div
          style={{
            fontFamily: "var(--font-jetbrains-mono), monospace",
            fontSize: "clamp(9px, 0.9vw, 11px)",
            letterSpacing: "0.18em",
            textTransform: "uppercase",
            color: "var(--blue)",
            marginBottom: 14,
          }}
        >
          ■ Zama FHEVM · Sepolia Testnet
        </div>
        <h1
          style={{
            fontWeight: 700,
            fontSize: "clamp(26px, 3.4vw, 46px)",
            lineHeight: 1.1,
            margin: "0 0 16px",
            letterSpacing: "-0.005em",
            color: "var(--ink)",
          }}
        >
          Seal your tokens.
          <br />
          <em style={{ fontWeight: 500, color: "var(--red)" }}>Let them age in private.</em>
        </h1>
        <p
          style={{
            color: "var(--muted)",
            margin: "0 0 20px",
            fontSize: "clamp(13px, 1.2vw, 16px)",
            maxWidth: 460,
            lineHeight: 1.5,
            textWrap: "pretty",
          }}
        >
          A ledger of official ERC-20 ⇄ ERC-7984 wrapper pairs. Wrap a public token and its balance vanishes from the
          chain&apos;s open books — fully encrypted, fully yours.
        </p>
        <div
          style={{
            display: "flex",
            gap: 20,
            alignItems: "baseline",
            fontFamily: "var(--font-jetbrains-mono), monospace",
            color: "var(--ink)",
          }}
        >
          <span style={{ fontSize: "clamp(10px, 1vw, 13px)" }}>
            <strong style={{ fontSize: "clamp(15px, 1.8vw, 24px)", color: "var(--red)" }}>{pairCount}</strong> pairs
            listed
          </span>
          <span style={{ fontSize: "clamp(10px, 1vw, 13px)" }}>
            <span style={{ color: "var(--green)" }}>●</span> registry live
          </span>
        </div>
      </div>

      {/* VISUAL — looping cellar frame (video if present, else Ken-Burns still). */}
      <div className="hero-visual">
        {HERO_VIDEO ? (
          <video
            src={HERO_VIDEO}
            poster="/01-hero.png"
            autoPlay
            loop
            muted
            playsInline
            aria-hidden="true"
            preload="metadata"
          />
        ) : (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src="/01-hero.png"
            alt="Engraved illustration of a stone cellar with bottles aging on wooden racks"
            className="hero-kenburns"
          />
        )}
      </div>
    </section>
  );
}
